Change plugin name
membraneframework/membrane_caps_audio_raw pull request #23
Opened 2022-02-28 12:41 UTC by dimamik

2022-02-28 13:28 UTC, dimamik commented
Probably GitHub repo name also needs to be changed

2022-03-01 17:47 UTC, mickel8 requested changes

2022-03-01 17:47 UTC, mickel8 commented on README.md
> +{:membrane_raw_audio_format, "~> 0.6.1"}
We need to update badges too so 
```
[![Hex.pm](https://img.shields.io/hexpm/v/membrane_raw_audio_format.svg)](https://hex.pm/packages/membrane_raw_audio_format)
[![API Docs](https://img.shields.io/badge/api-docs-yellow.svg?style=flat)](https://hexdocs.pm/membrane_raw_audio_format)
[![CircleCI](https://circleci.com/gh/membraneframework/membrane_raw_audio_format/tree/master.svg?style=svg)](https://circleci.com/gh/membraneframework/membrane_raw_audio_format/tree/master)
```

and the link at the end

```
[![Software Mansion](https://logo.swmansion.com/logo?color=white&variant=desktop&width=200&tag=membrane-github)](https://swmansion.com/?utm_source=git&utm_medium=readme&utm_campaign=membrane_raw_audio_format)
```

2022-03-01 17:47 UTC, mickel8 commented on README.md
>  Copyright 2018, [Software Mansion](https://swmansion.com/?utm_source=git&utm_medium=readme&utm_campaign=membrane)
```suggestion
Copyright 2018, [Software Mansion](https://swmansion.com/?utm_source=git&utm_medium=readme&utm_campaign=membrane_raw_audio_format)
```

2022-03-01 17:47 UTC, mickel8 commented on mix.exs
> +      extras: ["README.md", LICENSE: [title: "License"]],
We haven't used `title` option so far so I would leave it as it was :thinking:

2022-03-01 17:47 UTC, mickel8 commented on mix.exs
>  defmodule Membrane.Caps.Audio.Raw.Mixfile do
```suggestion
defmodule Membrane.RawAudio.Mixfile do
```

2022-03-01 17:47 UTC, mickel8 commented on mix.exs
>        nest_modules_by_prefix: [Membrane.Caps]
```suggestion
      nest_modules_by_prefix: [Membrane.RawAudio]
```

2022-03-01 17:47 UTC, mickel8 commented on test/membrane_raw_audio_test.exs
> +  alias Membrane.RawAudio, as: RawAudio
```suggestion
  alias Membrane.RawAudio
```

2022-03-01 17:47 UTC, mickel8 commented on test/membrane_raw_audio/format_spec.exs
> +  alias Membrane.RawAudio.Format, as: Format
```suggestion
  alias Membrane.RawAudio.Format
```

2022-03-01 17:48 UTC, mickel8 commented on mix.exs
> +      extras: ["README.md", LICENSE: [title: "License"]],
Maybe except,`membrane_raw_video_format` :thinking:

2022-03-02 13:48 UTC, mickel8 approved these changes

2022-03-02 14:11 UTC, merged